### ISSUE TITLE
GUN Emblems seems to be broken again in v1.1.1

### ISSUE THREAD

**Issue by ViperAcidZX** [shaddatic/sa2b-render-fix#34] opened 2023-07-04 05:44 UTC
I just did a re-install of this mod to update to v1.1.1 and the GUN emblems on robots don't appear anymore when they did worked in the previous version of this mod.

**Comment by shaddatic** [comment] 2023-07-04 08:08
I'm unable to reproduce this, have you checked it's not a mod conflict?

**Comment by shaddatic** [comment] 2023-07-04 21:27
Closing as unreproduceable

**Closed by shaddatic** 2023-07-04 21:27 UTC
Labels: unreproduceable

**Comment by ViperAcidZX** [comment] 2023-07-04 22:50
> I'm unable to reproduce this, have you checked it's not a mod conflict?

I was able to check and it seems to be caused by Firebow59's DC Beetles (which was deleted) and DC Shield Hunters mods; turning them off or uninstalling them fixes the problem. The thing that bothers me thought that SEEPs standalone Restore GUN Logo mod never had an issue with these two other mods by Firebow59 and takes away from being able to restore Dreamcast features back into the PC version.

**Comment by shaddatic** [comment] 2023-07-06 19:45
It's caused by Firebow replacing models that don't need to be replaced. This mod doesn't replace already replaced models to better support model changes, but if Firebow needlessly replaces the model with a broken version that's their mod to fix
