### ISSUE TITLE
Incorrect Speedline thickness

### ISSUE THREAD

**Issue by ConnoisseurDexterity** [shaddatic/sa2b-render-fix#109] opened 2024-08-06 19:44 UTC
DC SA2 has the speedlines a little thicker by default and when you're further from the player, the thickness increases. This is missing on the PC version and the speedlines are thinner.

Image 1 = DC
Image 2 = PC
![thick speedlines](https://github.com/user-attachments/assets/ccb07464-7512-4e0a-8422-d70c4dd56586)
![thick speedlines pc](https://github.com/user-attachments/assets/c9230414-231e-4582-81b6-de31e8b49c93)

**Comment by shaddatic** [comment] 2024-08-06 22:21
Closing as duplicate of issue #30

**Closed** 2024-08-06 22:21 UTC
Labels: duplicate
