### ISSUE TITLE
sa2 render fix breaks cutscene revamp

### ISSUE THREAD

**Issue by CrystalClear51** [shaddatic/sa2b-render-fix#117] opened 2024-08-18 11:13 UTC
the 16:9 cutscenes added from cutscene revamp are scaled back to 4:3 if sa2 render fix is enabled. Tried disabling all other mods and only keeping cutscene revamp and this enabled, issue still persists. All configuration settings are default. Issue started happening after downoading the latest 1.3.2 version of sa2 render fix

**Comment by shaddatic** [comment] 2024-08-18 15:01
You have the 'Force 4:3 Aspect Ratio' setting on in the 'Events' config section. This was added for v1.3.2 and this is the correct behavior. Closing as 'Working as Intended'

**Closed by shaddatic** 2024-08-18 15:01 UTC
Labels: inv-wai
