### ISSUE TITLE
Iron Gate lighting

### ISSUE THREAD

**Issue by user18081972** [shaddatic/sa2b-render-fix#71] opened 2024-02-10 19:44 UTC
The lighting in Iron Gate becomes bad (imo) when Fix Model Tints is on (also Match Dreamcast tint).
It creates an ugly seam on the floor where the lighting hard cuts brighter, and then darker again.
![OFF](https://github.com/shaddatic/sa2b-render-fix/assets/124319511/88bdab58-d30f-446a-a998-81cc0a0687e0)
![ON](https://github.com/shaddatic/sa2b-render-fix/assets/124319511/cbbb32a8-fd4c-4d68-a4e1-c43d84026ad4)

**Comment by shaddatic** [comment] 2024-02-10 21:30
This is likely caused by the Ginja model format being awful. To fix various tinting issues, I set Ginja models to use a default diffuse value, which is fine if every model set its own diffuse value; however it doesn't.

Not sure what to do about it, I'll experiment around to see if there's a solid solution without breaking the Ginja tinting issue

**Comment by shaddatic** [comment] 2024-02-16 02:25
This was fixed in the last commit

**Closed by shaddatic** 2024-02-16 02:25 UTC
Labels: model-tint, render-fix
