### ISSUE TITLE
Emblem particle

### ISSUE THREAD

**Issue by Meepmeep189** [shaddatic/sa2b-render-fix#31] opened 2023-07-02 22:32 UTC
In the HD version of the game, the particles that display on the screen are stuck behind the emblem rather than circling around it.

![6057e10f26ab4](https://github.com/shaddatic/sa2b-render-fix/assets/90574700/2f0ffbf0-988b-4ab5-a5a2-fcefc7106aac)
![6057e10e628aa](https://github.com/shaddatic/sa2b-render-fix/assets/90574700/e8357e2c-ea15-471b-98d6-68a08e320323)

**Comment by shaddatic** [comment] 2023-07-03 05:20
Duplicate of issue #4 , closing. Thanks for the report

**Closed by shaddatic** 2023-07-03 05:20 UTC
Labels: duplicate
